name: textlint
on:
  push:
    branches:
      - "feature/**"
jobs:
  textlint:
    name: textlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node/npm
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: textlint-github-check
        uses: tsuyoshicho/action-textlint@v3
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          textlint_flags: "textlint --rulesdir=. --ignore-path=\"./.textlintignore\" \"../**/*.md\" "
        working-directory: textlint
      - name: textlint-github-pr-review
        uses: tsuyoshicho/action-textlint@v3
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          textlint_flags: "textlint --rulesdir=. --ignore-path=\"./.textlintignore\" \"../**/*.md\" "
        working-directory: textlint